module.exports = {
  DISABLE_ARCHIVE: '--no-archive',
  DUALS: 'duals',
  EMPTY_LINE: /^([\W]+)$/,
  FEMALE: 'female',
  GET_JUDGES: /(Judge [0-9]+[\(A-Za-z&\)]*): ?([A-Za-z \,]+)/,
  GET_HEAD_JUDGE: /(Head Judge:) ?([A-Za-z\,]+)/,
  GET_COURSE: /(Course:) ?([A-Za-z\,]+)/,
  GET_LENGTH: /(Length:) ?([0-9 m]+)/,
  GET_TECHNICAL_DELEGATE: /(T\.D\.:) ?([A-Za-z\,]+)/,
  GET_CHIEF_OF_COMP: /(Chief of Comp:) ?([A-Za-z\,]+)/,
  GET_CHIEF_OF_SCORING: /(Chief of Scoring:) ?([A-Za-z\,]+)/,
  GET_PACE: /(Pace:) ?([A-Za-z0-9 =\,\.]+)/,
  IS_SINGLES: /(singles|Singles)/,
  IS_SOURCE_FILE: /(txt|htm|html)$/,
  IS_RESULTS_TOP_BAR: /([=]{18})/,
  IS_DUALS: /(duals|Duals)/,
  IS_MAIN_RESULTS_ROW: /([0-9]) ?([0-9]+) ?([A-Z]+),([A-Za-z]+)/,
  MALE: 'male',
  NORTHSTAR_HINT: /nor.?/i,
  NORTHSTAR: "Northstar",
  SINGLES: 'singles',
  SQUAW_HINT: /OLY.?|SQU.?/i,
  SQUAW_VALLEY: 'Squaw Valley',
  WASATCH_HINT: /was.?/i,
  WASATCH: 'Wasatch'
};
